// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(two_mls_pqFFI)
import two_mls_pqFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_two_mls_pq_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_two_mls_pq_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTwoMlsPqInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * MLS cipher suite identified by its IANA-registered u16 value (RFC 9420 §17.1).
 * Private-range values (0xF000–0xFFFF) are used for suites pending IANA assignment.
 */
public protocol MlsCipherSuiteProtocol: AnyObject, Sendable {
    
    /**
     * True if this suite is the classical component of a Combiner pair (0x0003).
     * When a key package with this suite is paired with an ML-KEM-768 key package,
     * both belong to TwoMLS as a `CombinerKeyPackage` — do not route the classical
     * half to mls-rs-uniffi-ios independently.
     */
    func isCombinerClassical()  -> Bool
    
    /**
     * True if this suite is handled by TwoMLS as the PQ component of a session.
     * Use `is_combiner_classical` to identify the classical half of a Combiner pair
     * before routing — do not route a Combiner classical KP to mls-rs-uniffi-ios.
     */
    func isSupported()  -> Bool
    
    /**
     * The raw IANA-registered (or private-range) u16 value.
     */
    func value()  -> UInt16
    
}
/**
 * MLS cipher suite identified by its IANA-registered u16 value (RFC 9420 §17.1).
 * Private-range values (0xF000–0xFFFF) are used for suites pending IANA assignment.
 */
open class MlsCipherSuite: MlsCipherSuiteProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_two_mls_pq_fn_clone_mlsciphersuite(self.handle, $0) }
    }
    /**
     * Construct from a raw IANA cipher suite value.
     */
public convenience init(value: UInt16) {
    let handle =
        try! rustCall() {
    uniffi_two_mls_pq_fn_constructor_mlsciphersuite_new(
        FfiConverterUInt16.lower(value),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_two_mls_pq_fn_free_mlsciphersuite(handle, $0) }
    }

    
    /**
     * MLS_128_ML_KEM_768_AES128GCM_SHA256_Ed25519 (0xFDEA, FIPS 203)
     */
public static func mlKem768() -> MlsCipherSuite  {
    return try!  FfiConverterTypeMlsCipherSuite_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_constructor_mlsciphersuite_ml_kem_768($0
    )
})
}
    
    /**
     * MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 (0x0001)
     */
public static func x25519Aes128() -> MlsCipherSuite  {
    return try!  FfiConverterTypeMlsCipherSuite_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_constructor_mlsciphersuite_x25519_aes128($0
    )
})
}
    
    /**
     * MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519 (0x0003)
     */
public static func x25519Chacha() -> MlsCipherSuite  {
    return try!  FfiConverterTypeMlsCipherSuite_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_constructor_mlsciphersuite_x25519_chacha($0
    )
})
}
    

    
    /**
     * True if this suite is the classical component of a Combiner pair (0x0003).
     * When a key package with this suite is paired with an ML-KEM-768 key package,
     * both belong to TwoMLS as a `CombinerKeyPackage` — do not route the classical
     * half to mls-rs-uniffi-ios independently.
     */
open func isCombinerClassical() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_mlsciphersuite_is_combiner_classical(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * True if this suite is handled by TwoMLS as the PQ component of a session.
     * Use `is_combiner_classical` to identify the classical half of a Combiner pair
     * before routing — do not route a Combiner classical KP to mls-rs-uniffi-ios.
     */
open func isSupported() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_mlsciphersuite_is_supported(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * The raw IANA-registered (or private-range) u16 value.
     */
open func value() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_mlsciphersuite_value(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsCipherSuite: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MlsCipherSuite

    public static func lift(_ handle: UInt64) throws -> MlsCipherSuite {
        return MlsCipherSuite(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MlsCipherSuite) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsCipherSuite {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MlsCipherSuite, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsCipherSuite_lift(_ handle: UInt64) throws -> MlsCipherSuite {
    return try FfiConverterTypeMlsCipherSuite.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsCipherSuite_lower(_ value: MlsCipherSuite) -> UInt64 {
    return FfiConverterTypeMlsCipherSuite.lower(value)
}






/**
 * Holds an agent signing key and manages MLS key packages for publication.
 * The signing key's public component is the ClientId — the Basic Credential
 * that identifies this agent as a leaf node in MLS groups.
 */
public protocol TwoMlsPqClientProtocol: AnyObject, Sendable {
    
    /**
     * The ClientId (public signing key) for this agent.
     */
    func clientId()  -> ClientId
    
    /**
     * Generate a paired classical (0x0003) + PQ (0xFDEA) key package bundle
     * for use in the APQ/Combiner construction.
     */
    func generateCombinerKeyPackage() throws  -> CombinerKeyPackage
    
    /**
     * Generate a fresh KeyPackage for the given cipher suite.
     * Returns MLS-encoded bytes suitable for publication.
     * The corresponding HPKE private key is retained internally for group joins.
     */
    func generateKeyPackage(suite: MlsCipherSuite) throws  -> Data
    
}
/**
 * Holds an agent signing key and manages MLS key packages for publication.
 * The signing key's public component is the ClientId — the Basic Credential
 * that identifies this agent as a leaf node in MLS groups.
 */
open class TwoMlsPqClient: TwoMlsPqClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_two_mls_pq_fn_clone_twomlspqclient(self.handle, $0) }
    }
    /**
     * Create a TwoMlsPqClient from an existing agent signing key.
     */
public convenience init(signingKey: Data)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_constructor_twomlspqclient_new(
        FfiConverterData.lower(signingKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_two_mls_pq_fn_free_twomlspqclient(handle, $0) }
    }

    

    
    /**
     * The ClientId (public signing key) for this agent.
     */
open func clientId() -> ClientId  {
    return try!  FfiConverterTypeClientId_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqclient_client_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Generate a paired classical (0x0003) + PQ (0xFDEA) key package bundle
     * for use in the APQ/Combiner construction.
     */
open func generateCombinerKeyPackage()throws  -> CombinerKeyPackage  {
    return try  FfiConverterTypeCombinerKeyPackage_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqclient_generate_combiner_key_package(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Generate a fresh KeyPackage for the given cipher suite.
     * Returns MLS-encoded bytes suitable for publication.
     * The corresponding HPKE private key is retained internally for group joins.
     */
open func generateKeyPackage(suite: MlsCipherSuite)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqclient_generate_key_package(
            self.uniffiCloneHandle(),
        FfiConverterTypeMlsCipherSuite_lower(suite),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTwoMlsPqClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TwoMlsPqClient

    public static func lift(_ handle: UInt64) throws -> TwoMlsPqClient {
        return TwoMlsPqClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TwoMlsPqClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TwoMlsPqClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TwoMlsPqClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqClient_lift(_ handle: UInt64) throws -> TwoMlsPqClient {
    return try FfiConverterTypeTwoMlsPqClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqClient_lower(_ value: TwoMlsPqClient) -> UInt64 {
    return FfiConverterTypeTwoMlsPqClient.lower(value)
}






/**
 * A TwoMLSPQ session holding two asymmetric Combiner send groups.
 */
public protocol TwoMlsPqSessionProtocol: AnyObject, Sendable {
    
    func activeSessionId()  -> SessionId
    
    func archive() throws  -> Archive
    
    /**
     * Encrypt `app_message` using the PQ send group.
     * Must be called after `prepare_to_encrypt`; the pending proposal hash is used as
     * authenticated data and cleared on return.
     * When a commit was staged (did_commit: true), the output is a bundled commit+app message.
     */
    func encrypt(appMessage: Data) throws  -> EncryptResult
    
    /**
     * Process a message forwarded from another of the user's own devices.
     */
    func forwarded(headerDecrypted: Data) throws  -> MlsSenderMessage?
    
    func hasReceiveGroup()  -> Bool
    
    func isEstablished()  -> Bool
    
    func myAgentState()  -> AgentState
    
    /**
     * Welcome bytes to deliver to the remote party to complete group establishment.
     * Returns `None` once consumed or when both groups are live.
     */
    func pendingOutbound()  -> Data?
    
    /**
     * Prepare a pending proposal nonce and stage it for binding into the next outbound message.
     * Returns `Err(SessionNotReady)` until both groups are established.
     *
     * - `proposing: None` with a queued remote proposal → full commit (epoch advance + PSK refresh), `did_commit: true`
     * - `proposing: Some(new_id)` → rotation commit with new leaf credential, `did_commit: true`
     * - Otherwise → recv self-Update only, `did_commit: false`
     */
    func prepareToEncrypt(proposing: ClientId?) throws  -> PrepareEncryptResult
    
    /**
     * Process an incoming message.
     *
     * - APQWelcome (0x01) → join recv groups; `Ok(None)`
     * - Rotation commit+app (0x03) → advance send epoch then decrypt; `DecryptResult`
     * - Partial bundle (0x05) → advance send.pq then decrypt app; `DecryptResult`
     * - Full bundle (0x07) → epoch advance + PSK refresh then decrypt; `DecryptResult`
     * - MLS ciphertext → decrypt on recv_group.pq; `DecryptResult`
     */
    func processIncoming(ciphertext: Data) throws  -> DecryptResult?
    
    func proposalContext()  -> TwoMlsPqDigest?
    
    /**
     * Accept a remote proposal for the next epoch advance.
     * On the next `prepare_to_encrypt(None)` call, an empty commit will be staged.
     */
    func queueProposal(digest: TwoMlsPqDigest) throws 
    
    func receiveGroupId()  -> CombinerGroupId?
    
    func sendRendezvous() throws  -> RendezvousId?
    
    func shouldListenOn() throws  -> ListenChannels
    
    /**
     * Register a new agent client for the next rotation commit.
     * Call before `prepare_to_encrypt(Some(new_client.client_id()))`.
     */
    func stageRotation(newClient: TwoMlsPqClient) throws 
    
    func theirAgentState()  -> AgentState
    
}
/**
 * A TwoMLSPQ session holding two asymmetric Combiner send groups.
 */
open class TwoMlsPqSession: TwoMlsPqSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_two_mls_pq_fn_clone_twomlspqsession(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_two_mls_pq_fn_free_twomlspqsession(handle, $0) }
    }

    
    /**
     * Join a session from an APQWelcome produced by the remote `initiate`.
     * Retrieve this party's return Welcome via `pending_outbound`.
     */
public static func accept(client: TwoMlsPqClient, welcome: Data, theirKeyPackage: CombinerKeyPackage)throws  -> TwoMlsPqSession  {
    return try  FfiConverterTypeTwoMlsPqSession_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_constructor_twomlspqsession_accept(
        FfiConverterTypeTwoMlsPqClient_lower(client),
        FfiConverterData.lower(welcome),
        FfiConverterTypeCombinerKeyPackage_lower(theirKeyPackage),$0
    )
})
}
    
    /**
     * Restore a session from a serialised archive.
     */
public static func fromArchive(archive: Archive, client: TwoMlsPqClient)throws  -> TwoMlsPqSession  {
    return try  FfiConverterTypeTwoMlsPqSession_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_constructor_twomlspqsession_from_archive(
        FfiConverterTypeArchive_lower(archive),
        FfiConverterTypeTwoMlsPqClient_lower(client),$0
    )
})
}
    
    /**
     * Create a session as the initiating party targeting `their_key_package`.
     * Retrieve the outbound APQWelcome bytes via `pending_outbound`.
     */
public static func initiate(client: TwoMlsPqClient, theirKeyPackage: CombinerKeyPackage)throws  -> TwoMlsPqSession  {
    return try  FfiConverterTypeTwoMlsPqSession_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_constructor_twomlspqsession_initiate(
        FfiConverterTypeTwoMlsPqClient_lower(client),
        FfiConverterTypeCombinerKeyPackage_lower(theirKeyPackage),$0
    )
})
}
    

    
open func activeSessionId() -> SessionId  {
    return try!  FfiConverterTypeSessionId_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_active_session_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func archive()throws  -> Archive  {
    return try  FfiConverterTypeArchive_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_archive(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Encrypt `app_message` using the PQ send group.
     * Must be called after `prepare_to_encrypt`; the pending proposal hash is used as
     * authenticated data and cleared on return.
     * When a commit was staged (did_commit: true), the output is a bundled commit+app message.
     */
open func encrypt(appMessage: Data)throws  -> EncryptResult  {
    return try  FfiConverterTypeEncryptResult_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_encrypt(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(appMessage),$0
    )
})
}
    
    /**
     * Process a message forwarded from another of the user's own devices.
     */
open func forwarded(headerDecrypted: Data)throws  -> MlsSenderMessage?  {
    return try  FfiConverterOptionTypeMlsSenderMessage.lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_forwarded(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(headerDecrypted),$0
    )
})
}
    
open func hasReceiveGroup() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_has_receive_group(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isEstablished() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_is_established(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func myAgentState() -> AgentState  {
    return try!  FfiConverterTypeAgentState_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_my_agent_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Welcome bytes to deliver to the remote party to complete group establishment.
     * Returns `None` once consumed or when both groups are live.
     */
open func pendingOutbound() -> Data?  {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_pending_outbound(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Prepare a pending proposal nonce and stage it for binding into the next outbound message.
     * Returns `Err(SessionNotReady)` until both groups are established.
     *
     * - `proposing: None` with a queued remote proposal → full commit (epoch advance + PSK refresh), `did_commit: true`
     * - `proposing: Some(new_id)` → rotation commit with new leaf credential, `did_commit: true`
     * - Otherwise → recv self-Update only, `did_commit: false`
     */
open func prepareToEncrypt(proposing: ClientId?)throws  -> PrepareEncryptResult  {
    return try  FfiConverterTypePrepareEncryptResult_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_prepare_to_encrypt(
            self.uniffiCloneHandle(),
        FfiConverterOptionTypeClientId.lower(proposing),$0
    )
})
}
    
    /**
     * Process an incoming message.
     *
     * - APQWelcome (0x01) → join recv groups; `Ok(None)`
     * - Rotation commit+app (0x03) → advance send epoch then decrypt; `DecryptResult`
     * - Partial bundle (0x05) → advance send.pq then decrypt app; `DecryptResult`
     * - Full bundle (0x07) → epoch advance + PSK refresh then decrypt; `DecryptResult`
     * - MLS ciphertext → decrypt on recv_group.pq; `DecryptResult`
     */
open func processIncoming(ciphertext: Data)throws  -> DecryptResult?  {
    return try  FfiConverterOptionTypeDecryptResult.lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_process_incoming(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
open func proposalContext() -> TwoMlsPqDigest?  {
    return try!  FfiConverterOptionTypeTwoMlsPqDigest.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_proposal_context(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Accept a remote proposal for the next epoch advance.
     * On the next `prepare_to_encrypt(None)` call, an empty commit will be staged.
     */
open func queueProposal(digest: TwoMlsPqDigest)throws   {try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_queue_proposal(
            self.uniffiCloneHandle(),
        FfiConverterTypeTwoMlsPqDigest_lower(digest),$0
    )
}
}
    
open func receiveGroupId() -> CombinerGroupId?  {
    return try!  FfiConverterOptionTypeCombinerGroupId.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_receive_group_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sendRendezvous()throws  -> RendezvousId?  {
    return try  FfiConverterOptionTypeRendezvousId.lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_send_rendezvous(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func shouldListenOn()throws  -> ListenChannels  {
    return try  FfiConverterTypeListenChannels_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_should_listen_on(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Register a new agent client for the next rotation commit.
     * Call before `prepare_to_encrypt(Some(new_client.client_id()))`.
     */
open func stageRotation(newClient: TwoMlsPqClient)throws   {try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_method_twomlspqsession_stage_rotation(
            self.uniffiCloneHandle(),
        FfiConverterTypeTwoMlsPqClient_lower(newClient),$0
    )
}
}
    
open func theirAgentState() -> AgentState  {
    return try!  FfiConverterTypeAgentState_lift(try! rustCall() {
    uniffi_two_mls_pq_fn_method_twomlspqsession_their_agent_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTwoMlsPqSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TwoMlsPqSession

    public static func lift(_ handle: UInt64) throws -> TwoMlsPqSession {
        return TwoMlsPqSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TwoMlsPqSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TwoMlsPqSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TwoMlsPqSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqSession_lift(_ handle: UInt64) throws -> TwoMlsPqSession {
    return try FfiConverterTypeTwoMlsPqSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqSession_lower(_ value: TwoMlsPqSession) -> UInt64 {
    return FfiConverterTypeTwoMlsPqSession.lower(value)
}




/**
 * Opaque serialised session state. Restore via `TwoMlsPqSession.fromArchive(_:)`.
 */
public struct Archive: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension Archive: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArchive: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Archive {
        return
            try Archive(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Archive, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArchive_lift(_ buf: RustBuffer) throws -> Archive {
    return try FfiConverterTypeArchive.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArchive_lower(_ value: Archive) -> RustBuffer {
    return FfiConverterTypeArchive.lower(value)
}


/**
 * ATProto DID-scoped client identifier.
 */
public struct ClientId: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension ClientId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientId {
        return
            try ClientId(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClientId, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientId_lift(_ buf: RustBuffer) throws -> ClientId {
    return try FfiConverterTypeClientId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientId_lower(_ value: ClientId) -> RustBuffer {
    return FfiConverterTypeClientId.lower(value)
}


/**
 * Paired MLS group identifiers for the classical and PQ halves of one Combiner direction.
 */
public struct CombinerGroupId: Equatable, Hashable {
    public var classical: MlsGroupId
    public var pq: MlsGroupId

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(classical: MlsGroupId, pq: MlsGroupId) {
        self.classical = classical
        self.pq = pq
    }

    

    
}

#if compiler(>=6)
extension CombinerGroupId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCombinerGroupId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CombinerGroupId {
        return
            try CombinerGroupId(
                classical: FfiConverterTypeMlsGroupId.read(from: &buf), 
                pq: FfiConverterTypeMlsGroupId.read(from: &buf)
        )
    }

    public static func write(_ value: CombinerGroupId, into buf: inout [UInt8]) {
        FfiConverterTypeMlsGroupId.write(value.classical, into: &buf)
        FfiConverterTypeMlsGroupId.write(value.pq, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCombinerGroupId_lift(_ buf: RustBuffer) throws -> CombinerGroupId {
    return try FfiConverterTypeCombinerGroupId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCombinerGroupId_lower(_ value: CombinerGroupId) -> RustBuffer {
    return FfiConverterTypeCombinerGroupId.lower(value)
}


/**
 * Paired key package bundle for the APQ/Combiner construction.
 * `classical` is MLS-encoded for suite 0x0003 (X25519+ChaCha20Poly1305);
 * `pq` is MLS-encoded for suite 0xFDEA (ML-KEM-768).
 */
public struct CombinerKeyPackage: Equatable, Hashable {
    public var classical: Data
    public var pq: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(classical: Data, pq: Data) {
        self.classical = classical
        self.pq = pq
    }

    

    
}

#if compiler(>=6)
extension CombinerKeyPackage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCombinerKeyPackage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CombinerKeyPackage {
        return
            try CombinerKeyPackage(
                classical: FfiConverterData.read(from: &buf), 
                pq: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: CombinerKeyPackage, into buf: inout [UInt8]) {
        FfiConverterData.write(value.classical, into: &buf)
        FfiConverterData.write(value.pq, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCombinerKeyPackage_lift(_ buf: RustBuffer) throws -> CombinerKeyPackage {
    return try FfiConverterTypeCombinerKeyPackage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCombinerKeyPackage_lower(_ value: CombinerKeyPackage) -> RustBuffer {
    return FfiConverterTypeCombinerKeyPackage.lower(value)
}


/**
 * Result of processing a remote commit. `new_sender` is `None` in
 * steady-state commits where only the recipient rotated.
 */
public struct CommitResult: Equatable, Hashable {
    public var newSender: ClientId?
    public var newRecipient: ClientId

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(newSender: ClientId?, newRecipient: ClientId) {
        self.newSender = newSender
        self.newRecipient = newRecipient
    }

    

    
}

#if compiler(>=6)
extension CommitResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCommitResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CommitResult {
        return
            try CommitResult(
                newSender: FfiConverterOptionTypeClientId.read(from: &buf), 
                newRecipient: FfiConverterTypeClientId.read(from: &buf)
        )
    }

    public static func write(_ value: CommitResult, into buf: inout [UInt8]) {
        FfiConverterOptionTypeClientId.write(value.newSender, into: &buf)
        FfiConverterTypeClientId.write(value.newRecipient, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitResult_lift(_ buf: RustBuffer) throws -> CommitResult {
    return try FfiConverterTypeCommitResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitResult_lower(_ value: CommitResult) -> RustBuffer {
    return FfiConverterTypeCommitResult.lower(value)
}


/**
 * Returned by `process_incoming`. Fields are `None` when not applicable to
 * the message type (e.g. `application_message` is absent for proposals/commits).
 */
public struct DecryptResult: Equatable, Hashable {
    public var applicationMessage: MlsSenderMessage?
    public var proposal: QueuedRemoteProposal?
    public var remoteCommit: CommitResult?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(applicationMessage: MlsSenderMessage?, proposal: QueuedRemoteProposal?, remoteCommit: CommitResult?) {
        self.applicationMessage = applicationMessage
        self.proposal = proposal
        self.remoteCommit = remoteCommit
    }

    

    
}

#if compiler(>=6)
extension DecryptResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecryptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecryptResult {
        return
            try DecryptResult(
                applicationMessage: FfiConverterOptionTypeMlsSenderMessage.read(from: &buf), 
                proposal: FfiConverterOptionTypeQueuedRemoteProposal.read(from: &buf), 
                remoteCommit: FfiConverterOptionTypeCommitResult.read(from: &buf)
        )
    }

    public static func write(_ value: DecryptResult, into buf: inout [UInt8]) {
        FfiConverterOptionTypeMlsSenderMessage.write(value.applicationMessage, into: &buf)
        FfiConverterOptionTypeQueuedRemoteProposal.write(value.proposal, into: &buf)
        FfiConverterOptionTypeCommitResult.write(value.remoteCommit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptResult_lift(_ buf: RustBuffer) throws -> DecryptResult {
    return try FfiConverterTypeDecryptResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptResult_lower(_ value: DecryptResult) -> RustBuffer {
    return FfiConverterTypeDecryptResult.lower(value)
}


/**
 * Returned by `encrypt`.
 */
public struct EncryptResult: Equatable, Hashable {
    public var cipherText: Data
    public var sender: ClientId
    public var recipient: ClientId
    public var epoch: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cipherText: Data, sender: ClientId, recipient: ClientId, epoch: UInt64) {
        self.cipherText = cipherText
        self.sender = sender
        self.recipient = recipient
        self.epoch = epoch
    }

    

    
}

#if compiler(>=6)
extension EncryptResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptResult {
        return
            try EncryptResult(
                cipherText: FfiConverterData.read(from: &buf), 
                sender: FfiConverterTypeClientId.read(from: &buf), 
                recipient: FfiConverterTypeClientId.read(from: &buf), 
                epoch: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.cipherText, into: &buf)
        FfiConverterTypeClientId.write(value.sender, into: &buf)
        FfiConverterTypeClientId.write(value.recipient, into: &buf)
        FfiConverterUInt64.write(value.epoch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptResult_lift(_ buf: RustBuffer) throws -> EncryptResult {
    return try FfiConverterTypeEncryptResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptResult_lower(_ value: EncryptResult) -> RustBuffer {
    return FfiConverterTypeEncryptResult.lower(value)
}


public struct EpochRendezvous: Equatable, Hashable {
    public var epoch: UInt64
    public var rendezvousId: RendezvousId

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(epoch: UInt64, rendezvousId: RendezvousId) {
        self.epoch = epoch
        self.rendezvousId = rendezvousId
    }

    

    
}

#if compiler(>=6)
extension EpochRendezvous: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEpochRendezvous: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EpochRendezvous {
        return
            try EpochRendezvous(
                epoch: FfiConverterUInt64.read(from: &buf), 
                rendezvousId: FfiConverterTypeRendezvousId.read(from: &buf)
        )
    }

    public static func write(_ value: EpochRendezvous, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.epoch, into: &buf)
        FfiConverterTypeRendezvousId.write(value.rendezvousId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEpochRendezvous_lift(_ buf: RustBuffer) throws -> EpochRendezvous {
    return try FfiConverterTypeEpochRendezvous.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEpochRendezvous_lower(_ value: EpochRendezvous) -> RustBuffer {
    return FfiConverterTypeEpochRendezvous.lower(value)
}


/**
 * Combiner group IDs and per-epoch rendezvous channels the transport should
 * listen on. Returned by `should_listen_on`.
 */
public struct ListenChannels: Equatable, Hashable {
    public var sendGroup: CombinerGroupId
    public var rendezvousByEpoch: [EpochRendezvous]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sendGroup: CombinerGroupId, rendezvousByEpoch: [EpochRendezvous]) {
        self.sendGroup = sendGroup
        self.rendezvousByEpoch = rendezvousByEpoch
    }

    

    
}

#if compiler(>=6)
extension ListenChannels: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListenChannels: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListenChannels {
        return
            try ListenChannels(
                sendGroup: FfiConverterTypeCombinerGroupId.read(from: &buf), 
                rendezvousByEpoch: FfiConverterSequenceTypeEpochRendezvous.read(from: &buf)
        )
    }

    public static func write(_ value: ListenChannels, into buf: inout [UInt8]) {
        FfiConverterTypeCombinerGroupId.write(value.sendGroup, into: &buf)
        FfiConverterSequenceTypeEpochRendezvous.write(value.rendezvousByEpoch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListenChannels_lift(_ buf: RustBuffer) throws -> ListenChannels {
    return try FfiConverterTypeListenChannels.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListenChannels_lower(_ value: ListenChannels) -> RustBuffer {
    return FfiConverterTypeListenChannels.lower(value)
}


/**
 * MLS group identifier.
 */
public struct MlsGroupId: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension MlsGroupId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsGroupId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsGroupId {
        return
            try MlsGroupId(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MlsGroupId, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsGroupId_lift(_ buf: RustBuffer) throws -> MlsGroupId {
    return try FfiConverterTypeMlsGroupId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsGroupId_lower(_ value: MlsGroupId) -> RustBuffer {
    return FfiConverterTypeMlsGroupId.lower(value)
}


/**
 * Fields extracted from an MLS-encoded KeyPackage message.
 */
public struct MlsKeyPackage {
    public var clientId: ClientId
    public var cipherSuite: MlsCipherSuite

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(clientId: ClientId, cipherSuite: MlsCipherSuite) {
        self.clientId = clientId
        self.cipherSuite = cipherSuite
    }

    

    
}

#if compiler(>=6)
extension MlsKeyPackage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsKeyPackage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsKeyPackage {
        return
            try MlsKeyPackage(
                clientId: FfiConverterTypeClientId.read(from: &buf), 
                cipherSuite: FfiConverterTypeMlsCipherSuite.read(from: &buf)
        )
    }

    public static func write(_ value: MlsKeyPackage, into buf: inout [UInt8]) {
        FfiConverterTypeClientId.write(value.clientId, into: &buf)
        FfiConverterTypeMlsCipherSuite.write(value.cipherSuite, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsKeyPackage_lift(_ buf: RustBuffer) throws -> MlsKeyPackage {
    return try FfiConverterTypeMlsKeyPackage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsKeyPackage_lower(_ value: MlsKeyPackage) -> RustBuffer {
    return FfiConverterTypeMlsKeyPackage.lower(value)
}


/**
 * Decrypted application message with its verified sender identity.
 */
public struct MlsSenderMessage: Equatable, Hashable {
    public var appMessageData: Data
    public var senderClientId: ClientId
    public var epoch: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(appMessageData: Data, senderClientId: ClientId, epoch: UInt64) {
        self.appMessageData = appMessageData
        self.senderClientId = senderClientId
        self.epoch = epoch
    }

    

    
}

#if compiler(>=6)
extension MlsSenderMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsSenderMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsSenderMessage {
        return
            try MlsSenderMessage(
                appMessageData: FfiConverterData.read(from: &buf), 
                senderClientId: FfiConverterTypeClientId.read(from: &buf), 
                epoch: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MlsSenderMessage, into buf: inout [UInt8]) {
        FfiConverterData.write(value.appMessageData, into: &buf)
        FfiConverterTypeClientId.write(value.senderClientId, into: &buf)
        FfiConverterUInt64.write(value.epoch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsSenderMessage_lift(_ buf: RustBuffer) throws -> MlsSenderMessage {
    return try FfiConverterTypeMlsSenderMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsSenderMessage_lower(_ value: MlsSenderMessage) -> RustBuffer {
    return FfiConverterTypeMlsSenderMessage.lower(value)
}


/**
 * Parsed identities from a `CombinerKeyPackage`.
 * Both components must share the same `client_id`; mismatched identities are rejected.
 */
public struct ParsedCombinerKeyPackage {
    public var clientId: ClientId
    public var classicalSuite: MlsCipherSuite
    public var pqSuite: MlsCipherSuite

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(clientId: ClientId, classicalSuite: MlsCipherSuite, pqSuite: MlsCipherSuite) {
        self.clientId = clientId
        self.classicalSuite = classicalSuite
        self.pqSuite = pqSuite
    }

    

    
}

#if compiler(>=6)
extension ParsedCombinerKeyPackage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedCombinerKeyPackage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedCombinerKeyPackage {
        return
            try ParsedCombinerKeyPackage(
                clientId: FfiConverterTypeClientId.read(from: &buf), 
                classicalSuite: FfiConverterTypeMlsCipherSuite.read(from: &buf), 
                pqSuite: FfiConverterTypeMlsCipherSuite.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedCombinerKeyPackage, into buf: inout [UInt8]) {
        FfiConverterTypeClientId.write(value.clientId, into: &buf)
        FfiConverterTypeMlsCipherSuite.write(value.classicalSuite, into: &buf)
        FfiConverterTypeMlsCipherSuite.write(value.pqSuite, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedCombinerKeyPackage_lift(_ buf: RustBuffer) throws -> ParsedCombinerKeyPackage {
    return try FfiConverterTypeParsedCombinerKeyPackage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedCombinerKeyPackage_lower(_ value: ParsedCombinerKeyPackage) -> RustBuffer {
    return FfiConverterTypeParsedCombinerKeyPackage.lower(value)
}


/**
 * Returned by `prepare_to_encrypt`. The app layer must bind `proposal_hash`
 * into its plaintext before calling `encrypt`. `did_commit` is false when
 * stuck in a prior epoch (no pending remote proposal to commit).
 */
public struct PrepareEncryptResult: Equatable, Hashable {
    public var proposalHash: TwoMlsPqDigest
    public var committedRemoteClientId: ClientId?
    public var didCommit: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proposalHash: TwoMlsPqDigest, committedRemoteClientId: ClientId?, didCommit: Bool) {
        self.proposalHash = proposalHash
        self.committedRemoteClientId = committedRemoteClientId
        self.didCommit = didCommit
    }

    

    
}

#if compiler(>=6)
extension PrepareEncryptResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrepareEncryptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrepareEncryptResult {
        return
            try PrepareEncryptResult(
                proposalHash: FfiConverterTypeTwoMlsPqDigest.read(from: &buf), 
                committedRemoteClientId: FfiConverterOptionTypeClientId.read(from: &buf), 
                didCommit: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PrepareEncryptResult, into buf: inout [UInt8]) {
        FfiConverterTypeTwoMlsPqDigest.write(value.proposalHash, into: &buf)
        FfiConverterOptionTypeClientId.write(value.committedRemoteClientId, into: &buf)
        FfiConverterBool.write(value.didCommit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareEncryptResult_lift(_ buf: RustBuffer) throws -> PrepareEncryptResult {
    return try FfiConverterTypePrepareEncryptResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareEncryptResult_lower(_ value: PrepareEncryptResult) -> RustBuffer {
    return FfiConverterTypePrepareEncryptResult.lower(value)
}


/**
 * A remote proposal queued for app-layer acceptance. `sender` sent the
 * proposal; `proposing` is the client being proposed (differs when a client
 * proposes its own rotation). `context` is the receive group's group-ID hash,
 * used for ordering against the app-level sequence number.
 */
public struct QueuedRemoteProposal: Equatable, Hashable {
    public var digest: TwoMlsPqDigest
    public var sender: ClientId
    public var proposing: ClientId
    public var context: TwoMlsPqDigest

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(digest: TwoMlsPqDigest, sender: ClientId, proposing: ClientId, context: TwoMlsPqDigest) {
        self.digest = digest
        self.sender = sender
        self.proposing = proposing
        self.context = context
    }

    

    
}

#if compiler(>=6)
extension QueuedRemoteProposal: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQueuedRemoteProposal: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QueuedRemoteProposal {
        return
            try QueuedRemoteProposal(
                digest: FfiConverterTypeTwoMlsPqDigest.read(from: &buf), 
                sender: FfiConverterTypeClientId.read(from: &buf), 
                proposing: FfiConverterTypeClientId.read(from: &buf), 
                context: FfiConverterTypeTwoMlsPqDigest.read(from: &buf)
        )
    }

    public static func write(_ value: QueuedRemoteProposal, into buf: inout [UInt8]) {
        FfiConverterTypeTwoMlsPqDigest.write(value.digest, into: &buf)
        FfiConverterTypeClientId.write(value.sender, into: &buf)
        FfiConverterTypeClientId.write(value.proposing, into: &buf)
        FfiConverterTypeTwoMlsPqDigest.write(value.context, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueuedRemoteProposal_lift(_ buf: RustBuffer) throws -> QueuedRemoteProposal {
    return try FfiConverterTypeQueuedRemoteProposal.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueuedRemoteProposal_lower(_ value: QueuedRemoteProposal) -> RustBuffer {
    return FfiConverterTypeQueuedRemoteProposal.lower(value)
}


/**
 * Transport rendezvous channel identifier.
 * Derived per epoch via `exportSecret(label="rendezvous", context="TwoMLS", len=32)`.
 */
public struct RendezvousId: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension RendezvousId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRendezvousId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RendezvousId {
        return
            try RendezvousId(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RendezvousId, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRendezvousId_lift(_ buf: RustBuffer) throws -> RendezvousId {
    return try FfiConverterTypeRendezvousId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRendezvousId_lower(_ value: RendezvousId) -> RustBuffer {
    return FfiConverterTypeRendezvousId.lower(value)
}


/**
 * Session identifier derived from both parties' client IDs at init time.
 * Both sides can derive the same ID independently, preventing identity
 * confusion when both parties initiate simultaneously.
 */
public struct SessionId: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension SessionId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionId {
        return
            try SessionId(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SessionId, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionId_lift(_ buf: RustBuffer) throws -> SessionId {
    return try FfiConverterTypeSessionId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionId_lower(_ value: SessionId) -> RustBuffer {
    return FfiConverterTypeSessionId.lower(value)
}


/**
 * Content-typed hash digest. Used by the app layer to identify and accept
 * MLS proposals before signalling back to the encryption layer.
 */
public struct TwoMlsPqDigest: Equatable, Hashable {
    public var hashType: UInt8
    public var digest: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hashType: UInt8, digest: Data) {
        self.hashType = hashType
        self.digest = digest
    }

    

    
}

#if compiler(>=6)
extension TwoMlsPqDigest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTwoMlsPqDigest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TwoMlsPqDigest {
        return
            try TwoMlsPqDigest(
                hashType: FfiConverterUInt8.read(from: &buf), 
                digest: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: TwoMlsPqDigest, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.hashType, into: &buf)
        FfiConverterData.write(value.digest, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqDigest_lift(_ buf: RustBuffer) throws -> TwoMlsPqDigest {
    return try FfiConverterTypeTwoMlsPqDigest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqDigest_lower(_ value: TwoMlsPqDigest) -> RustBuffer {
    return FfiConverterTypeTwoMlsPqDigest.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Credential state for one send direction. `Pending` means a rotation commit
 * was sent but the opposing side has not yet committed their half.
 */

public enum AgentState: Equatable, Hashable {
    
    case sync(clientId: ClientId
    )
    case pending(old: ClientId, new: ClientId
    )





}

#if compiler(>=6)
extension AgentState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgentState: FfiConverterRustBuffer {
    typealias SwiftType = AgentState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgentState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sync(clientId: try FfiConverterTypeClientId.read(from: &buf)
        )
        
        case 2: return .pending(old: try FfiConverterTypeClientId.read(from: &buf), new: try FfiConverterTypeClientId.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AgentState, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .sync(clientId):
            writeInt(&buf, Int32(1))
            FfiConverterTypeClientId.write(clientId, into: &buf)
            
        
        case let .pending(old,new):
            writeInt(&buf, Int32(2))
            FfiConverterTypeClientId.write(old, into: &buf)
            FfiConverterTypeClientId.write(new, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentState_lift(_ buf: RustBuffer) throws -> AgentState {
    return try FfiConverterTypeAgentState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentState_lower(_ value: AgentState) -> RustBuffer {
    return FfiConverterTypeAgentState.lower(value)
}



public enum TwoMlsPqError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Mls
    case InvalidKeyPackage
    case MissingWelcome
    case PskBinding
    case PqNotAvailable
    case SessionNotEstablished
    case SessionNotReady
    case ProposalRejected
    case DecryptionFailed
    case ArchiveInvalid

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension TwoMlsPqError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTwoMlsPqError: FfiConverterRustBuffer {
    typealias SwiftType = TwoMlsPqError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TwoMlsPqError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Mls
        case 2: return .InvalidKeyPackage
        case 3: return .MissingWelcome
        case 4: return .PskBinding
        case 5: return .PqNotAvailable
        case 6: return .SessionNotEstablished
        case 7: return .SessionNotReady
        case 8: return .ProposalRejected
        case 9: return .DecryptionFailed
        case 10: return .ArchiveInvalid

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TwoMlsPqError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Mls:
            writeInt(&buf, Int32(1))
        
        
        case .InvalidKeyPackage:
            writeInt(&buf, Int32(2))
        
        
        case .MissingWelcome:
            writeInt(&buf, Int32(3))
        
        
        case .PskBinding:
            writeInt(&buf, Int32(4))
        
        
        case .PqNotAvailable:
            writeInt(&buf, Int32(5))
        
        
        case .SessionNotEstablished:
            writeInt(&buf, Int32(6))
        
        
        case .SessionNotReady:
            writeInt(&buf, Int32(7))
        
        
        case .ProposalRejected:
            writeInt(&buf, Int32(8))
        
        
        case .DecryptionFailed:
            writeInt(&buf, Int32(9))
        
        
        case .ArchiveInvalid:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqError_lift(_ buf: RustBuffer) throws -> TwoMlsPqError {
    return try FfiConverterTypeTwoMlsPqError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTwoMlsPqError_lower(_ value: TwoMlsPqError) -> RustBuffer {
    return FfiConverterTypeTwoMlsPqError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeClientId: FfiConverterRustBuffer {
    typealias SwiftType = ClientId?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeClientId.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeClientId.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCombinerGroupId: FfiConverterRustBuffer {
    typealias SwiftType = CombinerGroupId?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCombinerGroupId.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCombinerGroupId.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCommitResult: FfiConverterRustBuffer {
    typealias SwiftType = CommitResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCommitResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCommitResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDecryptResult: FfiConverterRustBuffer {
    typealias SwiftType = DecryptResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDecryptResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDecryptResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMlsSenderMessage: FfiConverterRustBuffer {
    typealias SwiftType = MlsSenderMessage?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMlsSenderMessage.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMlsSenderMessage.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeQueuedRemoteProposal: FfiConverterRustBuffer {
    typealias SwiftType = QueuedRemoteProposal?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeQueuedRemoteProposal.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeQueuedRemoteProposal.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRendezvousId: FfiConverterRustBuffer {
    typealias SwiftType = RendezvousId?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRendezvousId.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRendezvousId.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTwoMlsPqDigest: FfiConverterRustBuffer {
    typealias SwiftType = TwoMlsPqDigest?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTwoMlsPqDigest.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTwoMlsPqDigest.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEpochRendezvous: FfiConverterRustBuffer {
    typealias SwiftType = [EpochRendezvous]

    public static func write(_ value: [EpochRendezvous], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEpochRendezvous.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EpochRendezvous] {
        let len: Int32 = try readInt(&buf)
        var seq = [EpochRendezvous]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEpochRendezvous.read(from: &buf))
        }
        return seq
    }
}
/**
 * Derive the session identifier for a pair of clients.
 * Both sides compute the same value from the same inputs regardless of who
 * initiated, allowing CommProtocol to deduplicate concurrent session initiations.
 */
public func deriveSessionId(myId: ClientId, theirId: ClientId)throws  -> SessionId  {
    return try  FfiConverterTypeSessionId_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_func_derive_session_id(
        FfiConverterTypeClientId_lower(myId),
        FfiConverterTypeClientId_lower(theirId),$0
    )
})
}
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_two_mls_pq_fn_func_version($0
    )
})
}
/**
 * Parse and validate a combiner key package pair.
 * Returns an error if the two components do not share the same client identity.
 */
public func parseCombinerKeyPackage(kp: CombinerKeyPackage)throws  -> ParsedCombinerKeyPackage  {
    return try  FfiConverterTypeParsedCombinerKeyPackage_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_func_parse_combiner_key_package(
        FfiConverterTypeCombinerKeyPackage_lower(kp),$0
    )
})
}
/**
 * Parse an MLS-encoded KeyPackage and extract its client identity and cipher suite.
 * Use `is_supported` on the returned suite to decide which library should handle it.
 */
public func parseMlsKeyPackage(bytes: Data)throws  -> MlsKeyPackage  {
    return try  FfiConverterTypeMlsKeyPackage_lift(try rustCallWithError(FfiConverterTypeTwoMlsPqError_lift) {
    uniffi_two_mls_pq_fn_func_parse_mls_key_package(
        FfiConverterData.lower(bytes),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_two_mls_pq_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_two_mls_pq_checksum_func_derive_session_id() != 62066) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_func_version() != 33499) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_func_parse_combiner_key_package() != 43275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_func_parse_mls_key_package() != 21071) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_mlsciphersuite_is_combiner_classical() != 42584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_mlsciphersuite_is_supported() != 26983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_mlsciphersuite_value() != 46029) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqclient_client_id() != 639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqclient_generate_combiner_key_package() != 54914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqclient_generate_key_package() != 11864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_active_session_id() != 37750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_archive() != 11184) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_encrypt() != 3107) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_forwarded() != 20430) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_has_receive_group() != 35549) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_is_established() != 41629) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_my_agent_state() != 25081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_pending_outbound() != 44057) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_prepare_to_encrypt() != 16181) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_process_incoming() != 41427) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_proposal_context() != 55198) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_queue_proposal() != 37099) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_receive_group_id() != 24855) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_send_rendezvous() != 16968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_should_listen_on() != 14163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_stage_rotation() != 59017) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_method_twomlspqsession_their_agent_state() != 37009) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_mlsciphersuite_ml_kem_768() != 8052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_mlsciphersuite_new() != 734) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_mlsciphersuite_x25519_aes128() != 61516) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_mlsciphersuite_x25519_chacha() != 46953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_twomlspqclient_new() != 61181) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_twomlspqsession_accept() != 19817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_twomlspqsession_from_archive() != 15551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_two_mls_pq_checksum_constructor_twomlspqsession_initiate() != 44812) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTwoMlsPqInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all