[book]
authors = ["Germ Network"]
title = "TwoMLSPQ"
language = "en"
src = "src"

[output.html]
default-theme = "navy"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
# git-repository-url = "https://github.com/germ-network/TwoMLS"

[preprocessor.mermaid]
command = "mdbook-mermaid"
